package org.crandor.game.node.entity.player.ai.pvp;

import org.crandor.game.container.impl.EquipmentContainer;
import org.crandor.game.content.skill.Skills;
import org.crandor.game.node.entity.combat.CombatSpell;
import org.crandor.game.node.entity.player.ai.AIPlayer;
import org.crandor.game.node.entity.player.link.SpellBookManager;
import org.crandor.game.node.item.Item;
import org.crandor.tools.RandomFunction;

public class PVPAIPBuilderUtils {
	
	public static void generateClass(AIPlayer p) {
		int combatType = RandomFunction.getRandom(2);
		switch(combatType) {
		case 0:
			buildArcherStats(p);
			buildArcherEquipment(p);
			break;
		case 1:
			buildMeleeStats(p);
			buildMeleeEquipment(p);
			break;
		case 2:
			//todo: magic
			setupWizard(p);
			buildWizardStats(p);
			buildWizardEquipment(p);
			break;
		case 3:
			//max rune
			buildMaxMeleeStats(p);
			buildMaxMeleeEquipment(p);
			break;
		}
		p.getInventory().add(new Item(385, 20));
		p.getProperties().setCombatLevel(126);

		p.getSkills().setLevel(Skills.PRAYER, 98);
		p.getSkills().setStaticLevel(Skills.PRAYER, 98);
		p.getSkills().updateCombatLevel();
		p.getAppearance().sync();
		correctHitpointsStat(p);
	}

	private static void buildWizardEquipment(AIPlayer p) {
		int[] weapons = {
				1381,
				4675,
		};
		int hat = -1;
		int platebody = -1;
		int platelegs = -1;
		int gloves = -1;
		int boots = -1;
		int set = RandomFunction.getRandom(2);
		switch(set) {
		//Blue set
		case 0:
			hat = 4089;
			platebody = 4091;
			platelegs = 4093;
			gloves = RandomFunction.getRandom(10) == 1 ? generateGloves() : 4095;
			boots = RandomFunction.getRandom(10) == 1 ? generateBoots() : 4097;
			break;
		//Red set
		case 1:
			hat = 4099;
			platebody = 4101;
			platelegs = 4103;
			gloves = RandomFunction.getRandom(10) == 1 ? generateGloves() : 4105;
			boots = RandomFunction.getRandom(10) == 1 ? generateBoots() : 4107;
			break;
		//White set
		case 2:
			hat = 4109;
			platebody = 4111;
			platelegs = 4113;
			gloves = RandomFunction.getRandom(10) == 1 ? generateGloves() : 4115;
			boots = RandomFunction.getRandom(10) == 1 ? generateBoots() : 4117;
			break;
		case 3:
			hat = 4708;
			platebody = 4712;
			platelegs = 44714;
			gloves = RandomFunction.getRandom(10) == 1 ? generateGloves() : 4095;
			boots = RandomFunction.getRandom(10) == 1 ? generateBoots() : 4097;
			break;
		}
		p.getEquipment().replace(new Item(hat), EquipmentContainer.SLOT_HAT);
		p.getEquipment().replace(new Item(platebody), EquipmentContainer.SLOT_CHEST);
		p.getEquipment().replace(new Item(platelegs), EquipmentContainer.SLOT_LEGS);
		p.getEquipment().replace(new Item(weapons[RandomFunction.random(weapons.length)]), EquipmentContainer.SLOT_WEAPON);
		p.getEquipment().replace(new Item(generateNecklace()), EquipmentContainer.SLOT_AMULET);
		p.getEquipment().replace(new Item(boots), EquipmentContainer.SLOT_FEET);
		p.getEquipment().replace(new Item(generateCape()), EquipmentContainer.SLOT_CAPE);
		p.getEquipment().replace(new Item(gloves), EquipmentContainer.SLOT_HANDS);
		System.out.println("WE ARE WEARING " + p.getEquipment().format() + " FOR " + p.getName());
	}

	private static void setupWizard(AIPlayer p) {
		//final int SPELL_IDS[] = new int[] {1, 4, 6, 8, 10, 14, 17, 20, 24, 27, 33, 38, 45, 48, 52, 55 };
		p.getProperties().setAutocastSpell(((CombatSpell) SpellBookManager.SpellBook.MODERN.getSpell(55)));
		p.getInventory().add(new Item(554, 1000)); //Fire runes
		p.getInventory().add(new Item(555, 1000)); //Water runes
		p.getInventory().add(new Item(556, 1000)); //Air runes
		p.getInventory().add(new Item(557, 1000)); //Earth runes
		p.getInventory().add(new Item(558, 1000)); //Mind runes
		p.getInventory().add(new Item(559, 1000)); //Body runes
		p.getInventory().add(new Item(560, 1000)); //Death runes
		p.getInventory().add(new Item(561, 1000)); //Nature runes
		p.getInventory().add(new Item(562, 1000)); //Chaos runes
		p.getInventory().add(new Item(563, 1000)); //Law runes
	}

	private static void buildWizardStats(AIPlayer p) {
		int magicLevel = RandomFunction.random(80, 98);
		int defenceLevel = RandomFunction.random(80, 98);

		p.getSkills().setLevel(Skills.MAGIC, magicLevel);
		p.getSkills().setStaticLevel(Skills.MAGIC, magicLevel);
		p.getSkills().setLevel(Skills.DEFENCE, defenceLevel);
		p.getSkills().setStaticLevel(Skills.DEFENCE, defenceLevel);

		p.getSkills().updateCombatLevel();
		p.getAppearance().sync();
		correctHitpointsStat(p);
	}


	private static void buildMeleeStats(AIPlayer p) {
		int attackLevel = RandomFunction.random(80, 98);
		int strengthLevel = RandomFunction.random(attackLevel - 10, attackLevel + 10);
		int defenceLevel = RandomFunction.random(60, 98);

		p.getSkills().setLevel(Skills.ATTACK, attackLevel);
		p.getSkills().setStaticLevel(Skills.ATTACK, attackLevel);
		p.getSkills().setLevel(Skills.STRENGTH, strengthLevel);
		p.getSkills().setStaticLevel(Skills.STRENGTH, strengthLevel);
		p.getSkills().setLevel(Skills.DEFENCE, defenceLevel);
		p.getSkills().setStaticLevel(Skills.DEFENCE, defenceLevel);

		p.getSkills().updateCombatLevel();
		p.getAppearance().sync();
		correctHitpointsStat(p);
	}

	private static void buildMeleeEquipment(AIPlayer p) {
		int[] helms = {
				1163, //Rune Full Helm
				3751, //Berserker Helm
				3753, //Warrior Helm
				10828,
				1038,
				4753,
				//TODO: No helm
		};
		int[] shield = {
				1185, //Rune sq shield
				1201, //Rune kiteshield
				6524, //Obsidian shield
				8850, //Rune defender
				11283, //dragonfire shield
				14767, //dragon defender
		};
		int[] platebody = {
				1113, //Rune chainmail.
				1127, //Rune platebody.
				10551,
				4757,
				11724,
				4720,
		};
		int[] platelegs = {
				1079, //Rune platelegs.
				4759,
				11726,
				1075,
		};
		p.getEquipment().replace(new Item(helms[RandomFunction.random(helms.length)]), EquipmentContainer.SLOT_HAT);
		p.getEquipment().replace(new Item(shield[RandomFunction.random(shield.length)]), EquipmentContainer.SLOT_SHIELD);
		p.getEquipment().replace(new Item(platebody[RandomFunction.random(platebody.length)]), EquipmentContainer.SLOT_CHEST);
		p.getEquipment().replace(new Item(platelegs[RandomFunction.random(platelegs.length)]), EquipmentContainer.SLOT_LEGS);
		p.getEquipment().replace(new Item(weapons[RandomFunction.random(weapons.length)]), EquipmentContainer.SLOT_WEAPON);
		p.getEquipment().replace(new Item(generateNecklace()), EquipmentContainer.SLOT_AMULET);
		p.getEquipment().replace(new Item(generateBoots()), EquipmentContainer.SLOT_FEET);
		p.getEquipment().replace(new Item(generateCape()), EquipmentContainer.SLOT_CAPE);
		p.getEquipment().replace(new Item(generateGloves()), EquipmentContainer.SLOT_HANDS);
	}

	public static final int[] weapons = {
			4151, //Whip
			4587, //Dragon Scimitar
			
	};


		private static void buildMaxMeleeStats(AIPlayer p) {

		p.getSkills().setLevel(Skills.ATTACK, 99);
		p.getSkills().setStaticLevel(Skills.ATTACK, 99);
		p.getSkills().setLevel(Skills.STRENGTH, 99);
		p.getSkills().setStaticLevel(Skills.STRENGTH, 99);
		p.getSkills().setLevel(Skills.DEFENCE, 99);
		p.getSkills().setStaticLevel(Skills.DEFENCE, 99);

		p.getSkills().updateCombatLevel();
		p.getAppearance().sync();
		correctHitpointsStat(p);
	}

	private static void buildMaxMeleeEquipment(AIPlayer p) {
		int[] helms = {
				3751, //Berserker Helm
		};
		int[] shield = {
				14767, //Dragon defender
		};
		int[] platebody = {
				11724, //Bandos chainmail.
		};
		int[] platelegs = {
				11726, //Bandos Tassets.
		};
		int[] amulets = {
				6585, //fury
		};
		int[] boots = {
				3105, //Climbing boots.
		};
		int[] cape = {
				6570, //Fire cape.
		};
		int[] gloves = {
				7462, //Barrows Gloves.
		};
		p.getEquipment().replace(new Item(helms[RandomFunction.random(helms.length)]), EquipmentContainer.SLOT_HAT);
		p.getEquipment().replace(new Item(shield[RandomFunction.random(shield.length)]), EquipmentContainer.SLOT_SHIELD);
		p.getEquipment().replace(new Item(platebody[RandomFunction.random(platebody.length)]), EquipmentContainer.SLOT_CHEST);
		p.getEquipment().replace(new Item(platelegs[RandomFunction.random(platelegs.length)]), EquipmentContainer.SLOT_LEGS);
		p.getEquipment().replace(new Item(weapons2[RandomFunction.random(weapons2.length)]), EquipmentContainer.SLOT_WEAPON);
		p.getEquipment().replace(new Item(amulets[RandomFunction.random(amulets.length)]), EquipmentContainer.SLOT_AMULET);
		p.getEquipment().replace(new Item(boots[RandomFunction.random(boots.length)]), EquipmentContainer.SLOT_FEET);
		p.getEquipment().replace(new Item(cape[RandomFunction.random(cape.length)]), EquipmentContainer.SLOT_CAPE);
		p.getEquipment().replace(new Item(gloves[RandomFunction.random(gloves.length)]), EquipmentContainer.SLOT_HANDS);
	}

	public static final int[] weapons2 = {
			4151, //Whip
	};

	private static void buildArcherStats(AIPlayer p) {
		int rangedLevel = RandomFunction.random(80, 98);
		int defenceLevel = RandomFunction.random(60, 98);

		p.getSkills().setLevel(Skills.RANGE, rangedLevel);
		p.getSkills().setStaticLevel(Skills.RANGE, rangedLevel);
		p.getSkills().setLevel(Skills.DEFENCE, defenceLevel);
		p.getSkills().setStaticLevel(Skills.DEFENCE, defenceLevel);

		p.getSkills().updateCombatLevel();
		p.getAppearance().sync();
		correctHitpointsStat(p);
	}

	private static void buildArcherEquipment(AIPlayer p) {
		int[] helms = {
				3749, //Archer helm
				2581,
				10828,
		};
		int[] weapons = {
				857, //Yew shortbow
				855, //Yew longbow
				861, //Magic shortbow
				859, //Magic longbow
				11235,
		};
		int[] arrows = {
				892, //Rune arrow
				11212,
		};
		int platebody = -1;
		int platelegs = -1;
		int gloves = -1;
		int set = RandomFunction.getRandom(2);
		switch(set) {
		//Blue set
		case 0:
			platebody = 2499;
			platelegs = 2493;
			gloves = RandomFunction.getRandom(10) == 1 ? generateGloves() : 2487;
			break;
		//Red set
		case 1:
			platebody = 2501;
			platelegs = 2495;
			gloves = RandomFunction.getRandom(10) == 1 ? generateGloves() : 2489;
			break;
		//Black set
		case 2:
			platebody = 2503;
			platelegs = 2497;
			gloves = RandomFunction.getRandom(10) == 1 ? generateGloves() : 2491;
			break;
		}
		p.getEquipment().replace(new Item(helms[RandomFunction.random(helms.length)]), EquipmentContainer.SLOT_HAT);
		p.getEquipment().replace(new Item(platebody), EquipmentContainer.SLOT_CHEST);
		p.getEquipment().replace(new Item(platelegs), EquipmentContainer.SLOT_LEGS);
		p.getEquipment().replace(new Item(weapons[RandomFunction.random(weapons.length)]), EquipmentContainer.SLOT_WEAPON);
		p.getEquipment().replace(new Item(generateNecklace()), EquipmentContainer.SLOT_AMULET);
		p.getEquipment().replace(new Item(generateBoots()), EquipmentContainer.SLOT_FEET);
		p.getEquipment().replace(new Item(generateCape()), EquipmentContainer.SLOT_CAPE);
		p.getEquipment().replace(new Item(gloves), EquipmentContainer.SLOT_HANDS);
		p.getEquipment().replace(new Item(arrows[RandomFunction.random(arrows.length)], 1000), EquipmentContainer.SLOT_ARROWS);
	}

	private static int generateCape() {
		int[] capes = {
				1007, //Red Cape
				1023, //Yellow Cape
				1019, //Black cape
				1021, //Blue cape
				1027, //Green cape
				1052, //Legends Cape
				2412, //Saradomin Cape
				2413, //Guthix Cape
				2414, //Zamorak Cape
				6570,
		};
		return capes[RandomFunction.random(capes.length)];
	}

	private static int generateNecklace() {
		int[] amulets = {
				1712, //Glory
				1725, //Strength ammy
				1727, //Amulet of magic
				1729, //Amulet of defence
				1478, //Amulet of accuracy
				6585,
		};
		return amulets[RandomFunction.random(amulets.length)];
	}

	private static int generateGloves() {
		int[] gloves = {
			1059,
			7462
		};
		return gloves[RandomFunction.random(gloves.length)];
	}

	private static int generateBoots() {
		int[] boots = {
				1061, //Leather boots.
				1837, //Desert boots.
				3105, //Climbing boots.
				3791, //Fremmy boots.
				11732,
		};
		return boots[RandomFunction.random(boots.length)];
	}

	private static void correctHitpointsStat(AIPlayer player) {
		player.getSkills().setLevel(Skills.HITPOINTS, 10);
		player.getSkills().setStaticLevel(Skills.HITPOINTS, 10);
		player.getSkills().updateCombatLevel();
			int rangedLevel = RandomFunction.random(80, 98);
			int defenceLevel = RandomFunction.random(80, 98);

			player.getSkills().setLevel(Skills.HITPOINTS, rangedLevel);
			player.getSkills().setStaticLevel(Skills.HITPOINTS, rangedLevel);
			player.getSkills().setLevel(Skills.HITPOINTS, defenceLevel);
			player.getSkills().setStaticLevel(Skills.HITPOINTS, defenceLevel);

			player.getSkills().updateCombatLevel();
			player.getAppearance().sync();
	}

	public static final String[] names = {
			"karamellioole123",
			"sillyninja20",
			"darkonecut0",
			"mars_noob",
			"volvovr0",
			"gagton23",
			"inkheart",
			"sock_flavour",
			"sophie72",
			"reaper_4me",
			"bessiedog",
			"brknsprk22",
			"whyuhackme",
			"rayvano55",
			"rayvano98",
			"zaborgttm",
			"warrior",
			"madsbang123",
			"christensen",
			"theboz87",
			"iqoigu2d",
			"f4ll3n0n3",
			"xbox360123",
			"stijnkessel",
			"kessel1996",
			"genderoni",
			"lolimawesome",
			"amac109",
			"downhill",
			"citricabyss",
			"ceesis",
			"terry1000666",
			"bink2468",
			"roman1248",
			"abcdefghijk",
			"superchunklz",
			"lizzie9",
			"fast_reflexx",
			"asherasher",
			"rebagon",
			"44b19n1v",
			"staylow",
			"nismo360",
			"tornoc109",
			"thunder20",
			"crosby_8127",
			"silhouette",
			"moltenore3",
			"lavabomb",
			"feedu_arrows",
			"soccer28",
			"mindkampfers",
			"notsogood",
			"ashbacher7",
			"tppcrpg7",
			"michaelsyer",
			"cue2hug",
			"drewno58",
			"13alls4ck",
			"j_p_13",
			"111robinson",
			"heyitstrea",
			"mccain",
			"doc_control",
			"fartmaster",
			"neonarg",
			"b9501175",
			"snorlax4",
			"jasonchou",
			"xgameboy95",
			"craig9596",
			"ojaste296lku123",
			"sheltzor",
			"karateboy11",
			"makkiestone",
			"billymon",
			"blackspidder",
			"sn1perh34ded",
			"jerzeythugz2",
			"trueset",
			"pure_x_400askaa1234",
			"mr_sgytkonyn",
			"twoitem",
			"1archerhbk",
			"assinass",
			"tharifica1",
			"apgart00",
			"fildherbn",
			"freeze112",
			"kno_way",
			"loloklol",
			"supermacho1",
			"09101991",
			"raptor8721",
			"justindb",
			"jolo5001",
			"catfish",
			"spiker991",
			"qpwoeiruty",
			"seasonsdawn",
			"seasonsend",
			"jartt2",
			"jartt1",
			"uber3pic",
			"doodoo12345",
			"rio1927ieman11",
			"angered_nubackers",
			"user_zim",
			"zacharyh1",
			"cool_kevin50",
			"4194ka",
			"freitty",
			"gamecube",
			"silver_knig0",
			"yourmom1",
			"beanroid",
			"smoke47149",
			"flitch289",
			"nooder000",
			"amazing_cake",
			"iridium",
			"aliffridzuan",
			"ridzuan2000",
			"bartez4",
			"k4eo9ssi7",
			"juxikeederast",
			"d_man_5567",
			"mod_richard",
			"q1w2e1r2",
			"be_kingless",
			"hardflip",
			"yami671",
			"fbr114",
			"rowelselidio",
			"gagoako",
			"haggishanger",
			"football1",
			"z_4_t_1_o_n",
			"sxngaming123",
			"simbojimbo",
			"digeryd00",
			"noob_10010",
			"giantpenis3959737",
			"dragonoid798",
			"qwerty798",
			"dylansuxnutz",
			"2016",
			"nigbittiesbro",
			"pk4lifefoo",
			"logieboi",
			"wichking",
			"kyros60r0bl33mfzo",
			"charlto1",
			"fmgh2145mvplesjack",
			"hiei179",
			"shadowx123",
			"seamus10990",
			"danward",
			"crusher16619",
			"doremember",
			"master15125",
			"ninjas11",
			"zarkotics",
			"saphira123",
			"skyler_is_on",
			"lolbobjo",
			"daniboom",
			"12345dani",
			"do_mhamai",
			"eoin3646",
			"rikuislove23",
			"denver23",
			"patacorow",
			"globalfun",
			"killer_ox08",
			"scott08",
			"persian_bossreston22",
			"gold_runmoon",
			"123456q",
			"nosweet15",
			"jefferson123 ",
			"applecore17",
			"mjc1997",
			"sayin68",
			"joshua123",
			"gray258ancakes",
			"somnus53",
			"antant123",
			"odysseu5",
			"gccdu58txs",
			"white1_ghost",
			"0622842800",
			"warriorasas",
			"bordtennis",
			"call911fro0b",
			"232323hi",
			"i_4_sp3c_k0",
			"anning12",
			"dante_dark3ossu44",
			"nifeman20",
			"fujifilm",
			"&pika_power08",
			"skiller2010",
			"quharas",
			"gogos123",
			"keatson",
			"dodgers5",
			"karils_starilgd001",
			"mjordan145",
			"02092006",
			"koth4356",
			"1989919899",
			"viperwind72",
			"3iderct1",
			"faeldora81",
			"naruto816",
			"colt_thunder",
			"tc1215",
			"bayat4life",
			"ali1234567",
			"daniel323a",
			"kxb69qjx",
			"1_rang3_pwns",
			"hwdpkonrad",
			"o1xaddicted",
			"abc123",
			"adam402",
			"498750",
			"gimberly8",
			"mrcoolio",
			"baister88",
			"meatball",
			"goodguard5",
			"29a11b96",
			"josh12508",
			"j39256",
			"bozzzerzzz",
			"nmwhuzrc",
			"volcomskate",
			"volcom",
			"jonny_ere_7",
			"ince78989",
			"pk_kinkyeachs",
			"vlad867",
			"vladstorm12",
			"justinhigg",
			"suilui62",
			"beastblade12",
			"hobbsey",
			"sticklysnipe",
			"bayview1",
			"snake_1464",
			"metalgear",
			"parklane79laystation",
			"ghtyrupekj",
			"jackryan",
			"hewitje",
			"halloroan",
			"pupucachu5",
			"spencer4123",
			"8bloodhollow",
			"ilovejesus",
			"hunting_slea",
			"h3llfire5",
			"dds_o_w_n_s",
			"9933230",
			"mankikned22",
			"kikulita",
			"skaleris3",
			"skaleriukas",
			"bluejay303",
			"codrocks",
			"bloodhalo11",
			"11272000",
			"maxsheld",
			"91330451",
			"jd4gray",
			"johnny12",
			"krisi129",
			"langbestur",
			"zadashi",
			"gearsfan",
			"jollyspace",
			"451901",
			"quekchose111",
			"5bp9mg",
			"maxsheld",
			"91330451",
			"frog1421",
			"sexrobot1421",
			"tomatos1",
			"drk34695",
			"chimpanze243",
			"undead0wner",
			"talald2",
			"86251234",
			"radicalluke",
			"kelly55",
			"lakertein",
			"metheman",
			"krissu127",
			"hyundai1",
			"jmannon00b1",
			"cheese1",
			"swirkstas",
			"rainislopas1",
			"gnarwaster1",
			"qrhvoq549",
			"loveburito",
			"carter22",
			"tiglasutru",
			"t1o2y3o4t5",
			"fangedbabyokemon1",
			"pijuitshorty",
			"marakasaya",
			"mr_funky_121",
			"joker45",
			"g_man",
			"william",
			"vexraill",
			"austin123",
			"pbcharger_85",
			"radilla1",
			"thepureryan",
			"121489ine",
			"lukasky",
			"lukecool",
			"dinbolir",
			"remember1",
			"swe_nintendo",
			"lew492car",
			"cody52368",
			"fr0nt1er",
			"xxandoxx2552",
			"liverpool1",
			"i_aduka_i",
			"lolowned",
			"downlar",
			"jjasjjas",
			"harrrocksrisonbreak",
			"cookies_ohh",
			"noseboy",
			"nickspie",
			"semmy12",
			"u_rock123412",
			"themind",
			"hi_im_tom9ooloop",
			"keatermy",
			"thomas98",
			"exemped",
			"ikbenyufei",
			"sum1udontno9",
			"kr0iznt0",
			"dark_rune195",
			"theoldnite",
			"savagelump",
			"kilosteak4",
			"lakwit17",
			"93444900",
			"pl0xables",
			"lemonade1",
			"leeboy262",
			"niniwee",
			"benosigmaaperisima",
			"kazokas7",
			"lopas123",
			"demonza1",
			"will00115",
			"lavaminer4",
			"meandme138",
			"twinkseypeshill5",
			"idrinkshakes",
			"rfyhyj6",
			"johnymuffin",
			"casey88",
			"rempicool",
			"admiraal1",
			"celayer",
			"bhboca2009",
			"seflarious",
			"teslatron",
			"artedhghtun",
			"freeze112",
			"pur3k0911",
			"footlong",
			"cooldude_x5",
			"toprak123",
			"cartoon_101",
			"kfauynoob",
			"okas5",
			"sittur",
			"el_sudado",
			"sudadera",
			"joeymaster93",
			"cookiej1",
			"thedrewboy12",
			"123123ha",
			"savior_4_u",
			"slutbomb",
			"jiwonbae1",
			"flameblaze",
			"xjordankr96x",
			"goodboy99",
			"solomon1103",
			"09102000",
			"omfgitsemo",
			"tr4p34",
			"marsh450rototype",
			"pellikanelliper",
			"messidonasef",
			"yoyododo",
			"selesan",
			"kovalev27",
			"n0_def_own_u",
			"hv650cou",
			"swarnes",
			"sntioi004",
			"snakeboy756",
			"0014702211",
			"seaviper101",
			"willow8520",
			"bradd1808",
			"smokey1808",
			"quintanamore",
			"momcatakers",
			"ahmarman",
			"doggydoodoo",
			"war4more",
			"stephens",
			"m3ntal_sh0ck",
			"nosam123",
			"tinybird02",
			"m1l1tary",
			"kill_guys",
			"jugheadellenn",
			"janieboy2",
			"kakhoofd123",
			"koedijk1",
			"lolliepop",
			"uhh_dead_k",
			"lehrman",
			"36dragon20",
			"izzi29040",
			"spuddman17",
			"nearhood",
			"ironedsockoleystr1",
			"hotviper6",
			"applesnakes6",
			"tyber3796",
			"nintendo1",
			"putther",
			"g9768241",
			"ynot_money",
			"superdude10",
			"pl0x____die",
			"c1tyw1ns",
			"rob1tooby1",
			"awesomeman2",
			"rsrownage",
			"welcome01",
			"smail154",
			"economie",
			"actualglory",
			"hello123",
			"x_gril8",
			"timmed1",
			"north1085",
			"jjn2008",
			"maximus_ivo",
			"1210729",
			"robzicles",
			"sk8ordie",
			"semanttinen",
			"koipallo",
			"zink22100",
			"toshiba1",
			"frylok_lol",
			"baseballftw",
			"flux_wolf",
			"glowx111",
			"haddon70",
			"jamaican13",
			"clivet_goth",
			"lol1lol1",
			"celsius91",
			"jonkka123",
			"kacj321",
			"9hjgyt83",
			"puzzlled456",
			"4elderwand",
			"moonbear98",
			"regitllij",
			"worsinksteeg",
			"logisung35",
			"kingescape22",
			"7dejulio",
			"sanka181",
			"campbell",
			"chikn_kikkr",
			"dinkdink",
			"zachdamaniak",
			"godzilla",
			"pk_mpskiller",
			"309251270",
			"pukkajoep",
			"sk1ttl35",
			"edparks10",
			"firemonkey4",
			"sasarrus",
			"superman1",
			"900_monster",
			"tealcrowd8",
			"sonicboom367",
			"wreckem",
			"burnt_c",
			"shadow123",
			"lv_egils",
			"qwerty12345",
			"thorodd",
			"zgergo",
			"hieveryone21",
			"snakesnakeoitsas",
			"neo34rd",
			"yl2bfbml",
			"tobi5q",
			"fredzio0",
			"qwerty2k3_n2",
			"allister3",
			"james13975",
			"movingon",
			"im_adored",
			"99str",
			"magicpinga12",
			"freminik",
			"chirinako",
			"miraculousmuppet",
			"joshj304",
			"m0t0r5h0w",
			"valor226",
			"empire2",
			"elliott9900",
			"meggie26",
			"kiteofdark",
			"ralph321",
			"kyrzani",
			"wsl63069",
			"0nly_4t_he4d",
			"marcao18",
			"kernivore",
			"born2bewild",
			"1_jeterfan",
			"goatmilk",
			"killer_gomez",
			"0007779",
			"sto__joni",
			"miljoona1",
			"kittehgod",
			"familyguy5",
			"airman521",
			"qwerty521",
			"draskiller",
			"123579jf",
			"good_guy2222",
			"jsl1983",
			"macauqe",
			"kabbible",
			"the_magius",
			"steven86",
			"a007lex1",
			"shadow581000",
			"fearless264",
			"61694jjl",
			"trevor600000",
			"trevorlee",
			"leimz",
			"konnad123",
			"mblais5",
			"nida17",
			"r_0_b_1annkook123",
			"hheadstrong",
			"tremayne",
			"goyzman",
			"jennifer123",
			"xleet_ninjax",
			"zachyb11",
			"adamdude333",
			"adam1997",
			"saat_pataa",
			"cra2f52z",
			"crazyidiot70",
			"jellybean",
			"plasma_guy4",
			"maxpower",
			"taohealin",
			"insane1992",
			"uhh_omg_obby",
			"llop6123",
			"edrash1",
			"alenho",
			"kent688",
			"fghjkl46",
			"123erer0",
			"rustydog23",
			"monstrs23",
			"roblox123",
			"soldbuffalo",
			"benxharris",
			"coen42",
			"mh2agewi",
			"specialguy16megama",
			"jo0_my_b33ch",
			"volcanic1",
			"stany35",
			"220198th",
			"motas23",
			"keese123",
			"swordblood3",
			"moomoo3",
			"davyandicall",
			"shakira",
			"paivmonster",
			"seven77",
			"sharpair",
			"a51thetruth",
			"lulzsux",
			"gabo2oo4m",
			"demon_ftwz",
			"chicken1252",
			"goodguard4",
			"29a11b96",
			"phonix260",
			"dragon123",
			"bencebence1",
			"19960227",
			"trainsgomoo4",
			"killhill",
			"lightness178",
			"xdpowerxd",
			"magican_owns",
			"0204492600",
			"sly_155",
			"dragonballz",
			"ssj4gogeta95",
			"eggnogg871",
			"kerfoogle",
			"football09",
			"mattfrank7",
			"1azsxdcfvgb",
			"invaliid3",
			"maolenmunn",
			"arkanoid0",
			"ftred432",
			"anonoumous1",
			"00100101",
			"i_have_wingz",
			"thibeault",
			"wolf_of_warr",
			"hurricane",
			"rauan78",
			"mental223",
			"kay_0wned",
			"9971282",
			"marththemage",
			"ssbmrules",
			"hcberryblitz",
			"uzumaki",
			"beast_rage9",
			"carbine666",
			"deadlydude46",
			"aardf1993",
			"sharper_arro",
			"imawesome1",
			"unholy1zero",
			"1w3e4r5",
			"i_pkernoob_i",
			"kirkyisko",
			"stift8",
			"jaapstam200",
			"takeda_iesyu",
			"h0lmg4rd",
			"im_to_low",
			"england123",
			"viniciusrub",
			"1224abb08e",
			"harris_0066",
			"james0066",
			"daretorparn",
			"volvo245",
			"didzydang",
			"hduerw",
			"idskillet",
			"ilovehalo1",
			"cows_moo34",
			"bigbang6",
			"el_brento9",
			"nightwing",
			"fireshot_co2",
			"bestest",
			"king5646uppylove",
			"max2531oepchinees",
			"kain581",
			"iecsf3hm",
			"heffman_13",
			"jl19605",
			"peep310",
			"ilovesanta",
			"agentds7okerface77",
			"kurithia",
			"readytodie",
			"ozzy_496",
			"shebagirl",
			"evilpk999",
			"hidalgo",
			"joker67tny",
			"demilover",
			"putles5",
			"lacina100",
			"redstone177",
			"bb123bb",
			"1hit1kill567",
			"1456327",
			"whiplashfan",
			"suzukits50",
			"vyndirya",
			"sjzipje96",
			"soapthrail",
			"killzs11",
			"i_hang_kids",
			"circaman1",
			"jason9918",
			"jasonw11",
			"austinz611",
			"azorn611",
			"zumerock",
			"kirara45",
			"abyssalite",
			"un1versal",
			"hellfire33k",
			"j067946409",
			"iron_vs_maul",
			"notrated7",
			"deadly_ghoul",
			"chad1990",
			"samie497",
			"walkersv",
			"sir_st77",
			"94387747pablitoz",
			"spijderkat",
			"vissen24",
			"blikbiermine",
			"medion123",
			"trixdig",
			"nixon995",
			"dragonwar729",
			"dragonwar123",
			"sc0rch1n_2h",
			"jagvet66",
			"apex_jrkspypk1",
			"leynell",
			"tresz134",
			"blocky_ownz",
			"ryan006",
			"king_batty_s",
			"godzilla",
			"very_bigfoot",
			"freded",
			"slyestcat",
			"zared45",
			"loko3610",
			"lucozade12",
			"edwarrior317",
			"thunderbolt17",
			"quietatrange",
			"alec123",
			"0_0_0wned_00",
			"doumdoum11",
			"jaxnarb",
			"darkness1",
			"achilles0009",
			"nathanok",
			"r4ngepr0fi",
			"leidinger",
			"torbjorn6",
			"google25me25",
			"42_to_doom",
			"leeong05",
			"jammer8009",
			"babybear",
			"standi96",
			"schakal1",
			"sucuraboii27",
			"ducks66",
			"15_years_now",
			"bleachfan",
			"xuan_yu31",
			"dcvhhvcd123",
			"jazabar",
			"772892ex",
			"arch_4_dutch",
			"zwart123",
			"dizzy_loot",
			"14racing",
			"grimmm125",
			"budgie88",
			"chrisj144",
			"chrisj92298",
			"sir_arfa",
			"arfaiscoolio",
			"pvp_rangers2",
			"skaiciuokle",
			"aka_t_rex",
			"kingdomkey0",
			"uncletom96",
			"cheese96",
			"matrix_men33",
			"matukka",
			"haleyboy1",
			"charlie21",
			"roooooosa",
			"kakajunn4444",
			"sacniv_zzzokemonas",
			"sint_gabriel",
			"iamsogoodnow",
			"nightwolf06",
			"thelandshark",
			"sirsparkles1elling123",
			"sergioshm",
			"wsaq3214",
			"sxe_ickis",
			"32210t86p",
			"sterling1717",
			"calvin1",
			"dwarfman666",
			"mynameis",
			"romeo_beller",
			"jess987",
			"bandion",
			"elhipfop",
			"adam_josiah",
			"vultures",
			"bloodydruid3oopklol",
			"majin125",
			"q78j2rps",
			"averykc",
			"woodshirt",
			"chemical711",
			"linkhero",
			"lord_fis0",
			"hejhejhej",
			"xvim999",
			"tazsucks",
			"colinmacray",
			"cool123",
			"zs102",
			"funkytown27",
			"croston10",
			"sexee666x",
			"jacob7767",
			"2669331",
			"charlto1",
			"fmgh2145mvplesjack",
			"&adam_c73",
			"bamboozled",
			"thegoge",
			"hot123qw",
			"puzzlled456",
			"4elderwand",
			"jrtiger297",
			"zekerdog1",
			"damexican99",
			"1124phc92",
			"tonganboyz1",
			"ironman54",
			"molson_1903",
			"y8h9i20j",
			"ketchupp9",
			"mustard",
			"shongo3258",
			"thunderbolt",
			"zammorak202",
			"54126635",
			"sword395",
			"suxsixdix1",
			"link_707",
			"joshua12397",
			"phenns",
			"robots100",
			"lucc666aspoort16",
			"luukielakke",
			"feyenoord",
			"rangeown1123",
			"joshienewtro",
			"fennell100",
			"bobdylan",
			"junitre1",
			"hidare22",
			"slasher954",
			"budflip12",
			"depredad0r",
			"656565",
			"shadowzrs",
			"narut0123",
			"grimmick15",
			"gowrangaownz",
			"ultima_9899",
			"1337master",
			"dominzdrac",
			"xxrunxx34",
			"sinduko",
			"baltimore",
			"machoman275",
			"y4ou21",
			"ahmedspy",
			"ahmed1992",
			"ronnie19l",
			"gilplatt97",
			"evil_miedo",
			"88nst0rm",
			"ejaeger99",
			"lilmanas",
			"oozaru66",
			"sanctuary",
			"dima638arool123",
			"nija646",
			"luke1998",
			"ditto110",
			"catdog97",
			"ebfft",
			"ekonesone",
			"morten_aj",
			"sootyimpy11",
			"money_boy688rton100",
			"happyheelas",
			"schema36",
			"samyett",
			"flapula123",
			"tony634ash12",
			"thedog77",
			"pascals123mgomgomg",
			"ikrissu",
			"eestimaa",
			"patrsa",
			"4po2sj",
			"morten_aj",
			"sootyimpy11",
			"danorah",
			"coolcat60",
			"crazywiteboi",
			"g5x74m8ss",
			"element11123",
			"25193469",
			"sawyer443swd1994",
			"pomojoona",
			"seliseli99",
			"yanumba1boi1",
			"43gb2im4",
			"that_guy503",
			"whatsdoin",
			"glennneke123",
			"cool123",
			"revolution04",
			"330330",
			"ryanl809",
			"asshass1",
			"gh0stsnyper",
			"chopper7",
			"pyro_fyro_0rinceton",
			"onilink992",
			"skyrim1234",
			"emsixteen",
			"19890910",
			"taeed24",
			"assassin12",
			"vi3t0wnage",
			"wolfpack450",
			"swarnes",
			"sntioi004",
			"lppalscore",
			"thebob55",
			"dhuurfa",
			"roflitsme",
			"astizzz",
			"58912b50",
			"manta566",
			"koirahullu",
			"robin5290",
			"jameswalker",
			"setiar1",
			"jesus123",
			"hej",
			"abbcab",
			"smegomeister",
			"sammson98",
			"dee_alster",
			"mynameisbob",
			"schadoxx",
			"hell4hell",
			"pk_mauzeris",
			"12211995",
			"sheepeater9",
			"knauer12345",
			"kartunez",
			"143256a",
			"machado123",
			"jayhay22",
			"jakee_bum",
			"4445poop",
			"smurfturf248",
			"jzadams",
			"arr0wpl0x",
			"wiirules1",
			"ryan01234",
			"donald21",
			"juoppoeki",
			"asami789",
			"dante_dark3ossu44",
			"joseph999159",
			"shadow1",
			"rubini98",
			"nutella1998",
			"lazyfaith",
			"qgy2o6",
			"mrwreckedem",
			"soccer1",
			"ty_the_ninja",
			"icychill",
			"blackeye446",
			"simonv3",
			"logiemac11",
			"maceachern1",
			"short_tastic",
			"blink182",
			"pops_mahone",
			"whitebtii",
			"war_eagle47",
			"mischief",
			"qazross",
			"dread46",
			"13wesley13",
			"warfight",
			"hellz_rader",
			"landman",
			"dakatt13",
			"nickname",
			"poop_o_nator",
			"0901257",
			"nummy_flame9",
			"magemage",
			"ads784",
			"bellonfire",
			"werslty",
			"tyler923",
			"bowslinger_9",
			"789987455",
			"chainmall",
			"jackson12398",
			"gurglesprainennydrop1",
			"legyplegyverboard99",
			"junkyboy55",
			"bindoosd",
			"gaomaster",
			"xuanhan",
			"danielmedvec",
			"123spill",
			"oddly_alive",
			"newyork",
			"babababoe",
			"runskape",
			"bigdunk69",
			"soccer13",
			"cat_prince25",
			"rockman",
			"paxton269",
			"22drp88",
			"uchihazen",
			"ihateyou111",
			"expo136",
			"alexpass",
			"peliset",
			"jfas97gv",
			"sords_4_life",
			"1011657",
			"krazy_kat575",
			"tigerflame",
			"aligindahose",
			"killforfood",
			"impzoren",
			"enter123",
			"dylan00117",
			"hotdog10",
			"bisinji",
			"rustysam",
			"tangle_golen",
			"02061996",
			"jijdwaas",
			"theelord",
			"varduka",
			"apina19",
			"chinadarkelf",
			"morrowind",
			"kickball83",
			"ilovekayla",
			"bradwoodward",
			"brad5420",
			"kriznar56",
			"machupichu56",
			"dezzilisk",
			"coldocean",
			"jorieboy3",
			"lwn13jk",
			"joneliux458",
			"5jega55",
			"celayer",
			"bhboca2009",
			"will753357liver4793",
			"gpunks3",
			"gmschool",
			"therayman940",
			"buddyboy",
			"schulpy",
			"chelsea1",
			"madfrk2222",
			"mmrabb1",
			"mattiege",
			"buster98",
			"monsterdany",
			"fs7312kp",
			"eldden",
			"252 625 26",
			"xbl33s_pk3rxortugal",
			"grotsnik4",
			"skulltaker",
			"peaceweazer",
			"sta10stik",
			"jordanator2",
			"maddydog1",
			"indomezu",
			"indasunay8",
			"chainlink66ieisgood11",
			"xchichimanx",
			"babychich",
			"rugissement",
			"glen123",
			"slayer78110",
			"calcetin",
			"drakeaumann",
			"eminem45",
			"voxyvax8563",
			"konvict",
			"niklasvegas",
			"videohai72",
			"elliotorin",
			"dadcabsxxx",
			"cw_range",
			"clanwars",
			"saynoob",
			"holland5",
			"fattyman_12",
			"77vettee",
			"tryharder4me",
			"lolatmyname",
			"native_ta_50",
			"blood4life",
			"xchichimanx",
			"babychich",
			"medevil_troy",
			"nigger311",
			"bobbobster6",
			"aolh8i",
			"wildboy1888",
			"9118747",
			"macacox",
			"12touchsuperett",
			"sonny585",
			"77vettee",
			"theprorspker",
			"1a2s3d4f5",
			"The Old Nite",
			"94cm442modrak96",
			"north_omaha",
			"southomaha",
			"ruindungeon",
			"fearoth",
			"gpgard15",
			"homies01",
			"kaz123kaz123",
			"bieniak0048",
			"bartez4",
			"k4eo9ssi7",
			"myroyalwings",
			"compact1157",
			"godawgs08",
			"dco14",
			"baddiekins",
			"gtrhro511",
			"devilman651",
			"georgekk9",
			"zain_winters",
			"158491122",
			"vovakova",
			"551879321",
			"mr0sharkie",
			"136qwerty136",
			"tylerrockis1",
			"yoyobaby",
			"bbmonke1honglu1",
			"armadylz_x",
			"wtfyounoob",
			"fille809",
			"0763595260",
			"mansonroks1",
			"manson1",
			"dubstepparty",
			"lmmikjki",
			"uniwide",
			"darkmage",
			"mandude65",
			"manduderules",
			"don_dalton",
			"bobutberg",
			"biscoito77",
			"15181996",
			"munkki345",
			"dfzrbrm7",
			"zarocks2",
			"henry6679",
			"nikdx",
			"99long",
			"smilly48",
			"blackout22",
			"im_not_afish",
			"1wiiwii",
			"javiercmh",
			"teno8181",
			"ancient_ttam",
			"shooter12",
			"str_poiss10",
			"k2tlin",
			"segraps",
			"12qwaszx",
			"nephew31",
			"hubbabubba",
			"guthix2569zzyjosh1234",
			"rulxman",
			"singapore",
			"frozenax7955",
			"noodles",
			"terumpk1",
			"hello101",
			"xyameax",
			"bert1127",
			"scottstimo",
			"sabop8",
			"destructo361",
			"13461618",
			"nikdx",
			"99long",
			"khanpop1",
			"khan2662",
			"lilboibryan",
			"dragon123",
			"benjo171",
			"spireite1",
			"king___joel",
			"monkey33",
			"kukko12",
			"kukkeli12",
			"swanepoel101",
			"luke081295",
			"mobuis_three",
			"mommys4",
			"zorzacken",
			"hookedon",
			"feetsoup",
			"forrest11",
			"lilsaint343",
			"0akwood",
			"krisalix",
			"karadic",
			"saisseh",
			"miskaman123",
			"eckbulldog",
			"ecknick2510",
			"cruel_guy2",
			"coolguy2",
			"jawad1144",
			"soldier123",
			"sebber43",
			"kiwiiscape",
			"darkshiv",
			"wert0980",
			"sp3c_m4ul3r",
			"covcov21",
			"rhinaboy",
			"dragon465",
			"crazy_nut45",
			"9687241",
			"trx_despair",
			"thethethe123",
			"x1atcha",
			"anthony",
			"mr_nart",
			"epicfail",
			"marti1101",
			"redfaction",
			"paulohare",
			"superman1",
			"m4_0wns",
			"juska123",
			"coopershaw14",
			"13scooter14",
			"viper_snake",
			"superfluous",
			"fender_love",
			"devoncallme",
			"thorax777",
			"stilton1",
			"reese55rinter0",
			"flyflip",
			"jarrod123",
			"blackeye446",
			"simonv3",
			"sircoolio",
			"stillsnoopanddre",
			"zimza_toes",
			"leonard9",
			"raza838",
			"deadlove",
			"jamsinkereewee50",
			"jatanoma",
			"lolnoobs1",
			"starcat2002",
			"i6560344",
			"tarapita",
			"ud2hnx6q",
			"xcowboys",
			"cowboys458",
			"elgaro12",
			"83ed04374",
			"logrono23",
			"logman23",
			"grundledib",
			"m3ath00ks",
			"ballum2mega123",
			"1w1ll0wna",
			"thebrazil",
			"patacorow",
			"globalfun",
			"savtej89",
			"elkgrove",
			"darth_nome",
			"5ofclubs",
			"ultraprono70",
			"niggerlips005",
			"tiili10",
			"07010701",
			"u_said_stick",
			"ibanez28",
			"lolxman123",
			"qwerty123",
			"rebel_goon",
			"chrome18",
			"shaunth3pur3",
			"whatthe",
			"ruagamer1212",
			"nothing1",
			"strownedyou6",
			"lolnoob",
			"willroley",
			"hdw77k69",
			"shortd00d",
			"d1014d",
			"mr_dark720artypooper",
			"copadon",
			"girordot",
			"converse_con",
			"bunny123",
			"shallowspace",
			"tums9182",
			"xxlpad",
			"arnis1996",
			"camo124501",
			"abcdefghijk",
			"i_druelennythug",
			"bonebreakerrikksuger",
			"karma_rebornpaassss",
			"katastrophi4",
			"wrighton5",
			"s_n_x_w",
			"thatiscool",
			"brusio",
			"516967853",
			"snakeboy756",
			"0014702211",
			"audiomonk",
			"drumstick",
			"sidekik123",
			"liban123",
			"nguyen374",
			"nguyen1996",
			"i_agsu_i",
			"jsjugb69",
			"jlventre",
			"denmarka4",
			"porto410ote1212",
			"carltyler1",
			"megadeth",
			"batzo",
			"qwerty88",
			"crystalfang3",
			"devin113",
			"lvl50_attack",
			"cherrim012",
			"kristaps288",
			"9792218",
			"rockyroller3",
			"harrytate2",
			"karrashimo",
			"never122",
			"necrovolt",
			"solovino1",
			"addpoke",
			"hpcdrt45",
			"hotsauce4299",
			"a1b2c3d4",
			"elblelbl",
			"djscratch",
			"spiderman_o",
			"kabsa23g",
			"grenade18",
			"goofygoober",
			"blueguy8989",
			"digimon8989",
			"dusty_granny",
			"naikyaone",
			"ffs_i_say_no",
			"erik123",
			"my_str_maax",
			"lukinhas",
			"tankbuster97",
			"tanksmash2",
			"eemuman",
			"nakkipate",
			"pk_zorbes",
			"mor1990",
			"dgfriend5",
			"456789abc",
			"twisternick6",
			"jason22",
			"alan22589",
			"gotmoney1",
			"noob_karil3",
			"ee11ee11",
			"elmo909",
			"focus123",
			"swordfury40",
			"stonecold9",
			"rey_rey_6116",
			"metsss11",
			"rebagon",
			"44b19n1v",
			"lava_viper_6",
			"lavaviper78",
			"taryn_blue1",
			"taryn71",
			"pluralgarths",
			"frederic123",
			"skeloperch",
			"zombieperch",
			"verrrtigo",
			"karolekas",
			"fuhq247",
			"6423694rocky",
			"bnarney",
			"fartingfag",
			"clicker882",
			"newbie882",
			"str_bonage",
			"minemunni135",
			"brsnip3rlapster10",
			"orangie_boi",
			"jamesd23",
			"legendy3",
			"ubernozle1",
			"maulz_w_t_f2",
			"lilzoee",
			"flyman821",
			"tomtiger647",
			"fishizle",
			"hellomoto",
			"sir_hepuli1",
			"j0n10nh0t0rn0t",
			"knight_alam",
			"nigahiga",
			"tors66",
			"stavar111",
			"ausdaniel",
			"bulldogs1",
			"o_he_shot_me",
			"fuckhead",
			"dan_10567",
			"dragzxasqw",
			"jeze666",
			"minarell1",
			"the_a97",
			"romeydog",
			"thegringo44",
			"smdsmd44",
			"dale_89",
			"2215077",
			"chrisroscher",
			"jagex13245",
			"rabye_str",
			"hopk1t02",
			"killangel0",
			"cheatx101",
			"grunt628",
			"asshole1",
			"wolf_boy247",
			"blompee123",
			"p_k_e_r_1_0",
			"mustang1",
			"99killerbull",
			"fireman",
			"jbird197",
			"jistheman12",
			"f__t__f",
			"hahamines66",
			"lkjhgfdsa420",
			"charlie1",
			"ilovehighlvl",
			"sedef4",
			"napplesauce",
			"tony1243",
			"biowarrior11",
			"jmaj6722",
			"klansman5",
			"young10",
			"dawnodarknes",
			"redalert",
			"negglesolbones22",
			"garrdrenn1",
			"gd2005",
			"draognzboy",
			"zippmeup",
			"oseart55",
			"starwars501",
			"xfrightknite",
			"jlidd8990",
			"master_pk260skar123",
			"3meister",
			"dragon13",
			"madevillemon",
			"20111993",
			"cupit11",
			"harinton7",
			"xrapidclawx",
			"jordie4",
			"aurocks14",
			"310051552",
			"dombomagexd",
			"midweek",
			"falconfan_24",
			"battlehero96",
			"charkrit019",
			"apple1901",
			"duongmaster",
			"johnny07",
			"recon783",
			"eraserface",
			"faxxx1",
			"nightfall64",
			"mrjiggles25",
			"7415001",
			"zarm3000",
			"xzsawq67",
			"final_pure_g",
			"zammy88",
			"redfox280attrock",
			"rodrigo_g_m",
			"daynnight",
			"mag3_kill4s",
			"magepwnsu",
			"prime_maggot",
			"almost1",
			"elkalibre",
			"b0n3cl1nkz",
			"radi100",
			"kamalkamal1",
			"i_newarcher",
			"nakniki1",
			"lord_shunoby",
			"2615948",
			"stinkerror",
			"dragondz",
			"crusher16619",
			"doremember",
			"3_run_range",
			"11011997",
			"robo1rocks",
			"rocco1998",
			"tomcat975",
			"hermano123",
			"sarlon7",
			"irish001",
			"aznballer66",
			"9312025",
			"killers455",
			"matthewmjk",
			"desparo2222",
			"yoelmejor",
			"md650epa1",
			"gonzalez",
			"inferno368",
			"rectamos",
			"aced52",
			"iwashere321",
			"goblin5530hjok123",
			"h4x_pl0xz0r",
			"suzukirm85",
			"jessinator18",
			"hamedarash",
			"uzi_of_doom",
			"8401397",
			"sotired",
			"tootfart64",
			"alphazone123",
			"ankouisme123",
			"daewoo45",
			"joshowns",
			"gundymonster",
			"meow111",
			"acidacre",
			"kappa100",
			"boeman75",
			"ethsaq2",
			"yorotomaru",
			"qwopzxnm7913",
			"im_not_afish",
			"1wiiwii",
			"2rubbish",
			"muslim786",
			"boomikiller",
			"daco2023",
			"knight_988",
			"wearefamily",
			"corbo999",
			"whiterat",
			"yaranzo5",
			"keller18",
			"nick4998",
			"jnrc3271",
			"rizeline55",
			"hradhrad",
			"lsufreak9",
			"lsutigers1",
			"lost_pker222",
			"facebookrule",
			"napplesauce",
			"tony1243",
			"13wesley13",
			"warfight",
			"chirinako",
			"miraculousmuppet",
			"tanked_you_l",
			"qazwsx123",
			"spence587",
			"spencer",
			"crabs_magee",
			"reaperr7",
			"kingspell",
			"969896250",
			"bewareof_me",
			"200102494g",
			"grundith",
			"jadranovo05",
			"numeris14",
			"goblinn8",
			"theepicscout",
			"sonic44",
			"&phat_dood5",
			"briansucks",
			"momrocker",
			"nutmeg60",
			"sp_i_r_i_t",
			"1heehtam2",
			"one_secret",
			"firedoor56",
			"wizcoltt",
			"merlinnus",
			"archebowz",
			"bn0du7cs",
			"outoftimewon",
			"snapple12",
			"gavistire",
			"098665chaz",
			"k_o_sorry",
			"cristianor7",
			"masta395",
			"indy340",
			"alvaroscary",
			"killa94",
			"mr_gandolff",
			"1968camero",
			"wizkidvic",
			"uk3dbg",
			"dgenx21388",
			"wwefan1994",
			"printingman",
			"kopieer",
			"humper123479",
			"mikey97",
			"davydude2",
			"92thesnack92",
			"pure0292",
			"king1234",
			"1_h8_n3rdz",
			"bedtime",
			"caveman422",
			"ilikepie87",
			"emosocks1",
			"5496931",
			"g2uypie",
			"enok210",
			"workrange_o",
			"latefriday",
			"surplus99",
			"shabahang",
			"jonnathan002",
			"jonny002",
			"132kickflip",
			"heelflip",
			"andrewfly89",
			"roland123",
			"&snypermatt69",
			"canucks2012",
			"youdie111",
			"1moretime",
			"dannyhxdman8",
			"theend1",
			"g__f__d",
			"2fast4you",
			"grundledib",
			"m3ath00ks",
			"zalvose",
			"assassins",
			"gangstabros8",
			"master13",
			"supanight",
			"leonard12317",
			"thefurrymage",
			"hotrod1994",
			"tim_but_dim",
			"1994tyrer",
			"woferiukas",
			"deividas",
			"failedgull",
			"goupia123",
			"inferno_1060",
			"vtech1060",
			"junk_king33",
			"junkguy",
			"racer_jaret",
			"callofduty4",
			"westorz",
			"741825963",
			"zenachue",
			"bomber357",
			"r4ngepr0fi",
			"leidinger",
			"kiryu36",
			"leo8lion",
			"monk_fights",
			"4991diddly",
			"boggom_8097",
			"garret1998",
			"svensktsnus",
			"asdaasda123",
			"ruudinho10",
			"hans19953109",
			"eltacolad",
			"bartlett",
			"esrb5",
			"candysex4",
			"junk_king33",
			"junkguy",
			"vanquishwolf",
			"hubertas",
			"w_3_s_c_0_t",
			"dogtown4life",
			"10hp_clans",
			"zinedine",
			"vader11567",
			"thunder1",
			"rempicool",
			"admiraal1",
			"5cripter",
			"roverdog123",
			"stallion918",
			"5489621",
			"zeroz_pure",
			"buster77owned123",
			"north_omaha",
			"southomaha",
			"alexwars400",
			"starwars4",
			"pureskill714",
			"raheem600",
			"molson_1903",
			"y8h9i20j",
			"arromin",
			"scarm4a1",
			"ravenangel1",
			"lancaster",
			"willheath20",
			"canuyo2",
			"smokadadank",
			"5433285",
			"blkchocobo",
			"shalico101",
			"envious_soul",
			"setcapmoc6",
			"shepowndu",
			"sll41ygi",
			"shoot_here2",
			"triops1029",
			"bananaboy441",
			"mieszawski",
			"pur3iwillbe",
			"monkeystew",
			"toddy_the_pk",
			"brosis09",
			"logrono",
			"gorillazfgi",
			"b1itz3d",
			"samsung90",
			"blakkwizard",
			"mythodea",
			"toke223",
			"hamster223",
			"guyman123890",
			"donkeykong",
			"riduan34",
			"lekurde",
			"desiver2",
			"throw80",
			"silver_gunn",
			"masteravery",
			"darkhawk744",
			"cocoman6",
			"c0c0nutmilkeatrick0",
			"&dragon_j86",
			"1234567890a",
			"steriili_pk",
			"arsk4",
			"c_robert_t",
			"monster1234",
			"sirpericlesmfgwtf",
			"kiill42",
			"your1zax",
			"goliathsnail",
			"illidan",
			"balcattaboy",
			"corbin94",
			"vereza",
			"d3susama",
			"&fort_40",
			"moonlight7",
			"bobsmith909",
			"kellyrocks",
			"idirim",
			"rennmaus358",
			"latirem",
			"muthsera",
			"pur3man_v10",
			"duckcow1",
			"kanpar2",
			"vinimi",
			"slomdapom",
			"k8s2e7g4",
			"hi_on_420",
			"dillweed",
			"zellanisixy3000",
			"tozzel",
			"toypaj",
			"triblouge",
			"carsa100",
			"texasdingoasswd123",
			"donkie90",
			"nicolas123",
			"mag3_pur3_ko",
			"hayesbonin",
			"zedukas_x",
			"eligijus",
			"cbuity",
			"code515396",
			"wardmathias",
			"ritabob",
			"dubert4",
			"rooney11",
			"throwchance",
			"chance5",
			"karamellioole123",
			"sillyninja20",
			"darkonecut0",
			"mars_noob",
			"volvovr0",
			"gagton23",
			"inkheart",
			"sock_flavour",
			"sophie72",
			"reaper_4me",
			"bessiedog",
			"brknsprk22",
			"whyuhackme",
			"rayvano55",
			"rayvano98",
			"zaborgttm",
			"warrior",
			"madsbang123",
			"christensen",
			"theboz87",
			"iqoigu2d",
			"f4ll3n0n3",
			"xbox360123",
			"stijnkessel",
			"kessel1996",
			"genderoni",
			"lolimawesome",
			"amac109",
			"downhill",
			"citricabyss",
			"ceesis",
			"terry1000666",
			"bink2468",
			"roman1248",
			"abcdefghijk",
			"superchunklz",
			"lizzie9",
			"fast_reflexx",
			"asherasher",
			"rebagon",
			"44b19n1v",
			"staylow",
			"nismo360",
			"tornoc109",
			"thunder20",
			"crosby_8127",
			"silhouette",
			"moltenore3",
			"lavabomb",
			"feedu_arrows",
			"soccer28",
			"mindkampfers",
			"notsogood",
			"ashbacher7",
			"tppcrpg7",
			"michaelsyer",
			"cue2hug",
			"drewno58",
			"13alls4ck",
			"j_p_13",
			"111robinson",
			"heyitstrea",
			"mccain",
			"doc_control",
			"fartmaster",
			"neonarg",
			"b9501175",
			"snorlax4",
			"jasonchou",
			"xgameboy95",
			"craig9596",
			"ojaste296lku123",
			"sheltzor",
			"karateboy11",
			"makkiestone",
			"billymon",
			"blackspidder",
			"sn1perh34ded",
			"jerzeythugz2",
			"trueset",
			"pure_x_400askaa1234",
			"mr_sgytkonyn",
			"twoitem",
			"1archerhbk",
			"assinass",
			"tharifica1",
			"apgart00",
			"fildherbn",
			"freeze112",
			"kno_way",
			"loloklol",
			"supermacho1",
			"09101991",
			"raptor8721",
			"justindb",
			"jolo5001",
			"catfish",
			"spiker991",
			"qpwoeiruty",
			"seasonsdawn",
			"seasonsend",
			"jartt2",
			"jartt1",
			"uber3pic",
			"doodoo12345",
			"rio1927ieman11",
			"angered_nubackers",
			"user_zim",
			"zacharyh1",
			"cool_kevin50",
			"4194ka",
			"freitty",
			"gamecube",
			"silver_knig0",
			"yourmom1",
			"beanroid",
			"smoke47149",
			"flitch289",
			"nooder000",
			"amazing_cake",
			"iridium",
			"aliffridzuan",
			"ridzuan2000",
			"bartez4",
			"k4eo9ssi7",
			"juxikeederast",
			"d_man_5567",
			"q1w2e1r2",
			"be_kingless",
			"hardflip",
			"yami671",
			"fbr114",
			"rowelselidio",
			"gagoako",
			"haggishanger",
			"football1",
			"sonderby",
			"banjomus",
			"sagar448",
			"heroes12",
			"windkid62595",
			"lilly117",
			"kacj321",
			"9hjgyt83",
			"sly_ninja80",
			"waynegod13",
			"discombobu99",
			"rocky34",
			"zorontu",
			"xtaylorx",
			"zezimaki",
			"ilovelordi",
			"joey7x",
			"kaleb8598",
			"kruiness",
			"daisymay21",
			"paul77777izzapizza1",
			"cow_hearder",
			"kingdrag",
			"lama_007",
			"trojans1",
			"helslayer11",
			"roblox11",
			"knifebloody",
			"1092310923",
			"dansendeaap",
			"uiensoep",
			"pure_exz",
			"29038995scotland",
			"theysconator",
			"ysbrandve1",
			"chrissy_booy",
			"egghead",
			"supreme1511",
			"landis1511",
			"tharujusassword123",
			"jdablada",
			"ugotskills",
			"kewl_kid",
			"killer99",
			"nicknack60",
			"choffee12",
			"a007lex1",
			"shadow581000",
			"ecmxflawless",
			"twenty8",
			"roguewolf33",
			"firefox101",
			"kaare83_2",
			"korsvegen",
			"da_king1295",
			"xemnas1",
			"airwalk285",
			"archman",
			"sir_kieran12",
			"spiderpig08",
			"fasterthanyu",
			"asdflkj",
			"lihtsaber2",
			"joe00224",
			"fortress170",
			"centurion",
			"youmeyou4",
			"laxworld",
			"xxmrfixitxx",
			"killer55",
			"morags",
			"ericolde",
			"e_a_r_l_y_k0liverkerr",
			"benno_rules",
			"lotrftw5",
			"embrach",
			"meier007",
			"xxlpad",
			"arnis1996",
			"spike8342",
			"knuckles",
			"spit_fire469",
			"tuesday23",
			"jonahmonk",
			"blackma9ic",
			"manmage247",
			"kingcoke",
			"ourkornalmer64",
			"paulypauly22",
			"chickenpoo",
			"kis_a_legend",
			"samtr0n",
			"amigos39",
			"blackhole",
			"abc12pee",
			"zman1123",
			"mr_frost22",
			"bubby5522",
			"lauren_maher",
			"foamy1992",
			"robertwb69",
			"rwb691169187",
			"blackhart74",
			"sambone",
			"janreypogi1",
			"kakilala",
			"hairy_marry",
			"brucie123",
			"gaming_gypsy",
			"qwewqwewqwe",
			"pros_only",
			"killer29043",
			"night_raid89",
			"hershey",
			"dragan_man62",
			"sordman",
			"vaizakhter1",
			"19692000",
			"rob1tooby1",
			"awesomeman2",
			"papagal7",
			"cartof33",
			"lil_0ctog0n",
			"hi12",
			"matthew_1001",
			"elliemay",
			"krilitor",
			"charlesk",
			"rileymango",
			"882psauq",
			"wutknochen",
			"12muschel78",
			"ravincal",
			"warchief1",
			"joloplex",
			"scrubs93",
			"kelly_koehn",
			"goldrush",
			"0k_im_sorry",
			"david123",
			"zack494",
			"lima7277",
			"killermac234",
			"spartan",
			"sharmen24",
			"bigballs",
			"ricarddragon",
			"123123s",
			"illepappeft",
			"mapet123",
			"josh6621",
			"dragon6621",
			"p__0__0__n3",
			"bringmetolife",
			"silentblue5",
			"hardflip96",
			"cbosk8er",
			"getbuff",
			"steelbeast97",
			"ironbeast",
			"zarkima",
			"idioteque8",
			"goselink1989",
			"janlul123",
			"rocky1247",
			"rocklobster9",
			"supapwnage",
			"holden123",
			"vietboihao",
			"vietboi",
			"cutvision",
			"internet",
			"stinkerror",
			"dragondz",
			"robert_magic",
			"darlene2",
			"min_ko7",
			"kristian1998",
			"adami888",
			"tetramins",
			"godssent2",
			"shadow14",
			"sawingmotion",
			"drag00n",
			"devincm",
			"harder64",
			"mrcrowley676",
			"stevefry",
			"canadian_nrg",
			"elvens11",
			"dbl_m",
			"mattrox3",
			"redgoblin352",
			"beunard",
			"sonderby",
			"banjomus",
			"sagar448",
			"heroes12",
			"windkid62595",
			"lilly117",
			"kacj321",
			"9hjgyt83",
			"sly_ninja80",
			"waynegod13",
			"discombobu99",
			"rocky34",
			"zorontu",
			"xtaylorx",
			"zezimaki",
			"ilovelordi",
			"joey7x",
			"kaleb8598",
			"kruiness",
			"daisymay21",
			"paul77777izzapizza1",
			"cow_hearder",
			"kingdrag",
			"lama_007",
			"trojans1",
			"helslayer11",
			"roblox11",
			"knifebloody",
			"1092310923",
			"dansendeaap",
			"uiensoep",
			"pure_exz",
			"29038995scotland",
			"theysconator",
			"ysbrandve1",
			"chrissy_booy",
			"egghead",
			"supreme1511",
			"landis1511",
			"tharujusassword123",
			"jdablada",
			"ugotskills",
			"kewl_kid",
			"killer99",
			"nicknack60",
			"choffee12",
			"a007lex1",
			"shadow581000",
			"ecmxflawless",
			"twenty8",
			"roguewolf33",
			"firefox101",
			"kaare83_2",
			"korsvegen",
			"da_king1295",
			"xemnas1",
			"airwalk285",
			"archman",
			"sir_kieran12",
			"spiderpig08",
			"fasterthanyu",
			"asdflkj",
			"lihtsaber2",
			"joe00224",
			"fortress170",
			"centurion",
			"youmeyou4",
			"laxworld",
			"xxmrfixitxx",
			"killer55",
			"morags",
			"ericolde",
			"e_a_r_l_y_k0liverkerr",
			"benno_rules",
			"lotrftw5",
			"embrach",
			"meier007",
			"xxlpad",
			"arnis1996",
			"spike8342",
			"knuckles",
			"spit_fire469",
			"tuesday23",
			"jonahmonk",
			"blackma9ic",
			"manmage247",
			"kingcoke",
			"ourkornalmer64",
			"paulypauly22",
			"chickenpoo",
			"kis_a_legend",
			"samtr0n",
			"amigos39",
			"blackhole",
			"abc12pee",
			"zman1123",
			"mr_frost22",
			"bubby5522",
			"lauren_maher",
			"foamy1992",
			"robertwb69",
			"rwb691169187",
			"blackhart74",
			"sambone",
			"janreypogi1",
			"kakilala",
			"hairy_marry",
			"brucie123",
			"gaming_gypsy",
			"qwewqwewqwe",
			"pros_only",
			"killer29043",
			"night_raid89",
			"hershey",
			"dragan_man62",
			"sordman",
			"vaizakhter1",
			"19692000",
			"rob1tooby1",
			"awesomeman2",
			"papagal7",
			"cartof33",
			"lil_0ctog0n",
			"hi12",
			"matthew_1001",
			"elliemay",
			"krilitor",
			"charlesk",
			"rileymango",
			"882psauq",
			"wutknochen",
			"12muschel78",
			"ravincal",
			"warchief1",
			"joloplex",
			"scrubs93",
			"kelly_koehn",
			"goldrush",
			"0k_im_sorry",
			"david123",
			"zack494",
			"lima7277",
			"killermac234",
			"spartan",
			"sharmen24",
			"bigballs",
			"ricarddragon",
			"123123s",
			"illepappeft",
			"mapet123",
			"josh6621",
			"dragon6621",
			"p__0__0__n3",
			"bringmetolife",
			"silentblue5",
			"hardflip96",
			"cbosk8er",
			"getbuff",
			"steelbeast97",
			"ironbeast",
			"zarkima",
			"idioteque8",
			"goselink1989",
			"janlul123",
			"rocky1247",
			"rocklobster9",
			"supapwnage",
			"holden123",
			"vietboihao",
			"vietboi",
			"cutvision",
			"internet",
			"stinkerror",
			"dragondz",
			"robert_magic",
			"darlene2",
			"min_ko7",
			"kristian1998",
			"adami888",
			"tetramins",
			"godssent2",
			"shadow14",
			"sawingmotion",
			"drag00n",
			"devincm",
			"harder64",
			"mrcrowley676",
			"stevefry",
			"canadian_nrg",
			"elvens11",
			"dbl_m",
			"mattrox3",
			"redgoblin352",
			"beunard"
	};

}
